config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts do
  	resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	validates :user_id, presence: true
	has_many :comments, dependent: :destroy
	belongs_to :user
	validates :image, presence: true 
	has_attached_file :image, styles: { :medium => "640x" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post

	def create
		@comment = @post.comments.build(comment_params)
		@comment.user_id = current_user.id 

		if @comment.save
			flash[:success] = "You commented the hell out of that post!"
			redirect_back(fallback_location: root_path)
		else
			flash[:alert] = "Check the comment form, something went horribly wrong."
			render root_path
		end
	end

	def destroy 
		@comment = @post.comments.find(params[:id])
		if current_user.id == @comment.user.id
			@comment.destroy
			flash[:success] = "Comment deleted :("
			redirect_to root_path
		else
			flash[:alert] = "That doesn't belong to you!"
			redirect_to root_path
		end
	end

	private 

	def set_post
		@post = Post.find(params[:post_id])
	end

	def comment_params
		params.require(:comment).permit(:content)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_post, only: [:edit, :update, :destroy, :show]
	before_action :owned_post, only: [:edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def new
		@post = current_user.posts.build
	end

	def edit
		
	end

	def update
		if @post.update(post_params)
			flash[:success] = "Post updated hombre."
			redirect_to post_path(@post)
		else
			flash[:alert] = "Something is wrong with your form!"
			render :edit
		end
	end

	def destroy
		if @post.destroy
			flash[:success] = "Problem solved! Post deleted."
			redirect_to posts_path
		else
			flash[:alert] = "Something went terribly wrong and deleting that nude selfie was not possible."
			render :edit
		end
	end

	def create 
		@post = current_user.posts.build(post_params)

		if @post.save
			flash[:success] = "Your post has been created."
			redirect_to posts_path
		else
			flash[:alert] = "Your new post couldn't be created!  Please check the form."
			render :new
		end

	end

	def show
	end

	private

	def post_params
		params.require(:post).permit(:caption, :image)
	end

	def find_post 
		@post = Post.find(params[:id])
	end

	def owned_post
		unless current_user == @post.user
			flash[:alert] = "That post doesn't belong to you!"
			redirect_to root_path
		end
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def alert_for(flash_type)
		{
			:success => "alert-success",
			:error => "alert-danger",
			:alert => "alert-warning",
			:notice => "alert-info"
		}[flash_type.to_sym] || flash_type.to_sym
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<div class="nav navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Photogram", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "New Post", new_post_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photogram</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
  	  <% flash.each do |name, msg| %>
  		  <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
  	  <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
	<div class="post">
		<div class="post-head">
			<div class="thumb-img">
				<div class="user-name">
					<%= post.user.user_name %>
				</div>
				<div>
					<%= time_ago_in_words post.created_at %>
				</div>
			</div>
		</div>
		<div class="image center-block">
			<%= link_to (image_tag post.image.url(:medium)), post_path(post), class: 'img-responsive' %>
		</div>
		<div class="post-bottom">
			<div class="caption">
				<div class="caption-content">
					<div class="user-name">
						<%= post.user.user_name %>
					</div>
					<%= post.caption %>
				</div>
				<% if post.comments %>
          			<% post.comments.each do |comment| %>
            			<div class="comment">
              				<div class="user-name">
                				<%= comment.user.user_name %>
              				</div>
              				<div class="comment-content">
                				<%= comment.content %>
              				</div>
              				<% if comment.user == current_user %>
                				<%= link_to "delete-#{comment.id}", post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } %>
              				<% end %>
            			</div>
          			<% end %>
        		<% end %>
        		<div class="comment-form">
          			<%= form_for [post, post.comments.new] do |f| %>
            			<%= f.text_field :content, placeholder: 'Add a comment...', id: "Comment" %>
            			<%= f.submit "Submit" %>
          			<% end %>
        		</div>
			</div>
		</div>
		<div class="comment-like-form row">
			<div class="like-button col-sm-1">
				<!-- <span>(class="glyphicon glyphicon-heart-empty")</span> -->
			</div>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="text-center">
	<%= image_tag @post.image.url(:medium) %>
</div>
<div class="form-wrapper">
	<%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true }  do |p| %>
		<div class="form-group">
			<%= p.input :image %>
		</div>
		<div class="form-group text-center">
			<%= p.input :caption %>
		</div>
		<div class="form-group text-center">
			<%= p.button :submit, class: 'btn-success' %>
		</div>
	<% end %>
</div>
<div class="text-center edit-links">
	<%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post" } %>
	<%= link_to "Cancel", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="posts-wrapper row">
	<% @posts.each do |p| %>
		<%= render 'post', post: p %>
	<% end %>
</div>

app/views/posts/new.html.erb
<div class="form-wrapper">
	<%= simple_form_for @post, html: { class: "form-horizontal", multipart: true } do |f| %>
		<div class="form-group">
			<%= f.input :image %>
		</div>
		<div class="form-group text-center">
			<%= f.input :caption %>
		</div>
		<div class="form-group text-center">
			<%= f.button :submit, class: "img-responsive" %>
		</div>
	<% end %>
</div>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
<div class="text-center edit-links">
	<% if @post.user.id == current_user.id %>
		<%= link_to 'Cancel', posts_path %>
		<%= link_to 'Edit Post', edit_post_path(@post) %>
	<% else %>
		<%= link_to 'Cancel', posts_path %>
	<% end %>
</div>
		